(bundle smartchr)
(add-hook 'lisp-mode-hook 'keicy-common-lisp-chrset)
(add-hook 'slime-repl-mode-hook 'keicy-common-lisp-chrset)

;;;; 大文字はC-M-b系のキーバインドで入力する.

(defun keicy-common-lisp-chrset ()
  (progn
    (local-set-key (kbd "A") (smartchr '("(apply `!!')" "A")))
    (local-set-key (kbd "C") (smartchr '("(cond `!!')" "C")))
    (local-set-key (kbd "D") (smartchr '("(defun `!!')" "(defvar `!!')" "(defmacro `!!')" "(defparameter `!!')" "D")))
    (local-set-key (kbd "E") (smartchr '("(eql `!!')" "(equal `!!')" "(equalp `!!')" "E")))
    (local-set-key (kbd "F") (smartchr '("(funcall `!!')" "F")))
    (local-set-key (kbd "G") (smartchr '("(getf `!!')" "G")))
    (local-set-key (kbd "I") (smartchr '("(if `!!')" "I")))
    (local-set-key (kbd "J") (smartchr '("(`!!')" "\"`!!'\"" "J")))
    (local-set-key (kbd "L") (smartchr '("(let ((`!!')))" "(loop `!!')" "L")))
    (local-set-key (kbd "Q") (smartchr '("'" "`" "Q")))
    (local-set-key (kbd "S") (smartchr '("(setf `!!')" "S")))
    (local-set-key (kbd "U") (smartchr '("(unless `!!')" "U")))
    (local-set-key (kbd "W") (smartchr '("(when `!!')" "W")))
    (local-set-key (kbd "#") (smartchr '("#'" "#")))
    (local-set-key (kbd "@") (smartchr '(",@" "`" "@")))
    (local-set-key (kbd ",") (smartchr '("," ",@")))
    (local-set-key (kbd "*") (smartchr '("*`!!'*" "*")))
  ))