(bundle smartchr)
(add-hook 'lisp-mode-hook 'keicy-common-lisp-chrset)
(add-hook 'slime-repl-mode-hook 'keicy-common-lisp-chrset)

(defun keicy-common-lisp-chrset ()
  (progn
    (local-set-key (kbd "C") (smartchr '("(cond `!!')" "C")))
    (local-set-key (kbd "E") (smartchr '("(eql `!!')" "(equal `!!')" "(equalp `!!')" "E")))
    (local-set-key (kbd "F") (smartchr '("(defun `!!')" "F")))
    (local-set-key (kbd "G") (smartchr '("(getf `!!')" "G")))
    (local-set-key (kbd "I") (smartchr '("(if `!!')" "I")))
    (local-set-key (kbd "J") (smartchr '("(`!!')" "J")))
    (local-set-key (kbd "L") (smartchr '("(let ((`!!')))" "(loop `!!')" "L")))
    (local-set-key (kbd "M") (smartchr '("(defmacro `!!')" "M")))
    (local-set-key (kbd "P") (smartchr '("(defparameter `!!')" "P")))
    (local-set-key (kbd "Q") (smartchr '("'" "`")))
    (local-set-key (kbd "S") (smartchr '("(setf `!!')" "S")))
    (local-set-key (kbd "U") (smartchr '("(unless `!!')" "U")))
    (local-set-key (kbd "V") (smartchr '("(defvar `!!')" "V")))
    (local-set-key (kbd "W") (smartchr '("(when `!!')" "W")))
    (local-set-key (kbd "#") (smartchr '("#'" "#")))
    (local-set-key (kbd "@") (smartchr '(",@" "`" "@")))
    (local-set-key (kbd ",") (smartchr '("," ",@")))
  ))
